version: '3.3'
services:
  database:
    container_name: vanDevTimesDB
    build: database
    environment:
      MYSQL_DATABASE: 'vanDevTimesDB'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'supersecret'
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:


